# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nickgen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(455, 311)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../source/appicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: #1b1b1b;")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(50, 30, 361, 41))
        self.lineEdit.setStyleSheet(".QLineEdit {\n"
"    background: rgb(80, 66, 136) ;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    width: 80%;\n"
"    outline: none;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    color: rgb(227, 227, 227);\n"
"}\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(50, 90, 361, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(100, 82, 170) ;\n"
"    color: #fff;\n"
"    border-radius: 20px;\n"
"    width: 80%;\n"
"    font-size: 20px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(77, 63, 131) ;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 220, 351, 71))
        self.label.setStyleSheet("font-size: 15px;\n"
"color: #fff;")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(121, 171, 211, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setStyleSheet("font-size: 15px;\n"
"color: #fff;\n"
"border-radius: 10px;")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(100, 82, 170);\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    width: 80%;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(77, 63, 131) ;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "NickName Generator by S-Mamashin"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Тут будет ваш ник"))
        self.pushButton.setText(_translate("Form", "Сгенерировать ник"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">Исходный код приложения, доступен на </span><a href=\"https://github.com/SMamashin/NickGenerator/\"><span style=\" text-decoration: underline; color:#ffaaff;\">GitHub</span></a></p><p><a href=\"https://github.com/SMamashin/NickGenerator/\"><span style=\" color:#ffffff; text-decoration: none;\">Приятного использования by S-Mamashin</span></a></p></body></html>"))
        self.checkBox.setText(_translate("Form", "Без _"))
        self.pushButton_3.setText(_translate("Form", "Женский"))
